services:
  - type: web
    name: evmAbis-api
    plan: free
    region: frankfurt
    runtime: node
    buildCommand: bun i
    startCommand: bun run start:prod
    envVars:
      - key: MEM_LIMIT
        value: 512
      - key: TMP_PATH
        value: /tmp
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: BASESCAN_API_KEY
        sync: false
      - key: POLYGONSCAN_API_KEY
        sync: false
      - key: OPTIMISMSCAN_API_KEY
        sync: false
      - key: ARBISCAN_API_KEY
        sync: false
      - key: BSCSCAN_API_KEY
        sync: false
      - key: FTMSCAN_API_KEY
        sync: false
      - key: NPM_TOKEN
        sync: false
    healthCheckPath: /monitoring/heartbeat
    autoDeploy: true
    domains:
      - evm-abis.xyz
